import json

from backend.planner.schemas import ExecutionPlan


class PlannerParser:
    """Parse JSON generated by the planner model."""

    def parse(self, response: str) -> ExecutionPlan:
        data = json.loads(response)
        return ExecutionPlan.model_validate(data)